### ISSUE TITLE
Flint/String Meshes

### ISSUE THREAD

**Issue by Hakameda** [Quantum64/ExGregilo#25]
Would it be possible to add string/Flint meshes for early stages of sieving. May be able to remove ex nigilo sieves from the early stages

**Comment by Quantum64** [comment]
Looks like I can add [flint ](https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/enums/Materials.java#L660) but not string unless I introduce a new GT material, which I don't really want to do.

**Comment by claws61821** [comment]
What about cotton or wool meshes as an alternative? That way you don't have to create a new GT material, and you can use mod compatibility to disable the Ex Nihilo string mesh when both mods are present. String is used to make wool, although I don't remember offhand whether it's used to make cotton as well. I think not, but I haven't played much in the past several months.

Wait... isn't String a vanilla item? Cotton > String > Wool? Why would you then need to make a GT material; or am I misunderstanding what you meant by that?

**Comment by Quantum64** [comment]
All the meshes for the advanced sieve are generated automatically based on the Gregtech metaitem system. I cannot add a new wire mesh that does not have an equivalent GT item without adding a new GT material. It's more of a technical reason.

**Comment by Hakameda** [comment]
Flint would probably be okay anyway

**Comment by claws61821** [comment]
Ah. I was indeed misunderstanding, then. So it's limited to materials which are already used in GT tool heads and GT ores? I assume you still have to tell the system which metaitems you want it to auto-generate meshes from?

**Comment by Quantum64** [comment]
Right. Not technically just materials used for tool heads. I can use any material that exists in here https://github.com/Blood-Asp/GT5-Unofficial/blob/ce4d0b705d682e85412741ac4e087413b75637ef/src/main/java/gregtech/api/enums/Materials.java

**Comment by Quantum64** [comment]
It basically falls on [this condition](https://github.com/Quantum64/ExGregilo/blob/master/src/main/java/co/q64/exgregilo/link/gregtech/tools/WireMesh.java#L31) which right now is set to add a recipie for any metal that has a durability value. I can simply add a flint condition there.

**Comment by Hakameda** [comment]
On the topic of that, is it possible to make a durability modifier? So we
could say 3x it or w/e

**Comment by Quantum64** [comment]
The durability multiplier for meshes is defined [here](https://github.com/Quantum64/ExGregilo/blob/master/src/main/java/co/q64/exgregilo/link/gregtech/tools/WireMesh.java#L68).

**Comment by Hakameda** [comment]
Can it be added as a configuration option? The durability and maybe click
modifier?

**Comment by Hakameda** [comment]
Just an overall modifier if that works, don't need individual ones

**Comment by claws61821** [comment]
Theoretically, rubber seems like it might make a good mesh, but it's not really a starting skyblock item.
Could be facetious and make a glass wire mesh... (yes, I KNOW that's not how fiberglass works) -- wait, scratch that, sand is listed but I think glass isn't.
Plastic... same category as rubber; sensible but not an early resource.
Oh. There's glass. Under Second Degree Compounds.

**Comment by Quantum64** [comment]
@Hakameda Possibly, I'd rather have the mod as balanced as possible out of the box so if you think the value should be changed then please contribute your ideas.

**Comment by Hakameda** [comment]
I'm going to test how it feels, if you don't mind a few test builds to play
with it. Figured it might be easier when you should be studying for a test
lol

**Comment by Quantum64** [comment]
https://github.com/Quantum64/ExGregilo/releases

The latest build is automatically posted here. exgregilo-latest.jar is a usable compiled mod.

**Comment by Hakameda** [comment]
Yup, but to play with and test would require a few changed builds, like a 2x, 3x 5x on the durabilty

**Comment by Quantum64** [comment]
Feel free to edit the value and submit a PR. A new build will be made.

**Comment by claws61821** [comment]
Finally looking back through the comments that were posted while I was writing my last, and the associated links.

So, you're currently coded to automatically create a mesh from every material with subtags === Metal && mDurability, and to not create a mesh for any other material. The three materials players are used to which that obviously excludes based on the list in the GT5 source, at least those I know offhand, are String, Flint, and Diamond. There's nothing inherently [i]wrong[/i] with that, but it might alienate those who suddenly don't know what material meshes to craft.

Rather than add a function just for Flint meshes alone, may I recommend instead adding one for select non-Metal materials and then naming several of those? An array or list, perhaps... If you choose to go down that route, I would suggest any or all of the following be added to your list:

Flint ... Diamond ... Rubber ... Plastic ... Glass ...

I believe I saw a few other materials in the list which are used in air and water filters IRL, but which I don't believe would work well for dry solid sifting. Perhaps they could be used for a different but related set of machines...

**Comment by claws61821** [comment]
An ArrayList and associated entry to the conditional tree have been added to WireMesh.java but require some touching-up. Gradle currently objects to one of the entries in the ArrayList because something is using the wrong -source version. #29

**Comment by Quantum64** [comment]
0b1010ff5d38c1c9fe0525aa7fca553b4f07f60a
